# Values used for the directory scan
watch_dir: "/home/emil/Projects/Tasker/test_dir/"
threshold_val: 1

# Values used for the caldav integration
url: # -- redacted -- # # Url for specific calendar
username: # -- redacted -- # # Gives it self
password: # -- redacted -- # # Might be deivece pass if 2FA is enabled

name: "Rydde op i 'Upload fra mobil'" # Name for the task

priority: 4 # Default priority (1 is highest, 9 is lowest, 0 is off)
